project:
  type: website
  output-dir: docs

website:
  title: "ritML"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css



